[package]
name = "druid-debugger"
version = "0.1.0"
authors = ["Manmeet Maan <manmeetmann2003@gmail.com>"]
edition = "2018"

[dependencies]
druid = { path = "../druid", features = ["im"] }
druid_simple_table = { git = "https://github.com/Maan2003/druid-simple-table" }
